### ISSUE TITLE
sane ignore options not working

### ISSUE THREAD

**Issue by dannyk08** [ggkovacs/gulp-sane-watch#46]
Hello! 
Love the plugin BUT could we get an integration || update of the recently available `ignored` option from [sane](https://github.com/amasad/sane#sanedir-options). It was added 14 days ago and this would really help out on this [user case](https://github.com/amasad/sane/issues/67#issuecomment-270221986)

thanks 😁 !!!

**Comment by ggkovacs** [comment]
```js
var gulp = require('gulp');
var saneWatch = require('gulp-sane-watch');

gulp.task('watch', function() {
    saneWatch('css/**/*.css', {
        saneOptions: {
            ignored: ...
        }
    }, function() {
        gulp.start('styles');
    }); 
});
```
